/**
 * Supabase Management API & Self-Hosting Provisioning Client
 */

export const SUPABASE_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS public."appSettings" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  induction BOOLEAN DEFAULT true,
  upcomingevent BOOLEAN DEFAULT false,
  upcomingeventstatus BOOLEAN DEFAULT true,
  smtp_host TEXT,
  smtp_port INT DEFAULT 465,
  smtp_user TEXT,
  smtp_pass TEXT,
  smtp_secure BOOLEAN DEFAULT true
);

CREATE TABLE IF NOT EXISTS public."events" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT,
  date DATE,
  time TEXT,
  location TEXT,
  speaker TEXT,
  is_competition BOOLEAN DEFAULT false,
  form_fields JSONB DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS public."eventsResponses" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  event_id BIGINT REFERENCES public."events"(id) ON DELETE CASCADE,
  name TEXT,
  nu_email TEXT,
  phone TEXT,
  batch TEXT,
  attendance BOOLEAN DEFAULT false,
  custom_responses JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public."competitionsResponses" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  event_id BIGINT REFERENCES public."events"(id) ON DELETE CASCADE,
  team_name TEXT,
  name TEXT,
  nu_email TEXT,
  phone TEXT,
  status BOOLEAN,
  attendance BOOLEAN DEFAULT false,
  custom_responses JSONB DEFAULT '{}'::jsonb
);

CREATE TABLE IF NOT EXISTS public."competitionWinners" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  event_id BIGINT REFERENCES public."events"(id) ON DELETE CASCADE,
  response_id BIGINT,
  position INT,
  team_name TEXT,
  name TEXT,
  nu_email TEXT
);

CREATE TABLE IF NOT EXISTS public."inductionResponses" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  nu_email TEXT NOT NULL,
  phone TEXT,
  domain TEXT,
  team_preferences TEXT,
  status BOOLEAN,
  interview_date TIMESTAMPTZ,
  notes TEXT
);

CREATE TABLE IF NOT EXISTS public."members" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  nu_email TEXT NOT NULL,
  phone TEXT,
  lead_id BIGINT,
  status BOOLEAN DEFAULT true,
  role TEXT DEFAULT 'Member'
);

CREATE TABLE IF NOT EXISTS public."leads" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT NOT NULL,
  email TEXT,
  domain TEXT,
  phone TEXT
);

CREATE TABLE IF NOT EXISTS public."contactResponses" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT,
  email TEXT,
  subject TEXT,
  message TEXT,
  status BOOLEAN
);

CREATE TABLE IF NOT EXISTS public."certificates" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  event_id BIGINT REFERENCES public."events"(id) ON DELETE CASCADE,
  recipient_name TEXT NOT NULL,
  recipient_email TEXT NOT NULL,
  certificate_code TEXT UNIQUE NOT NULL,
  certificate_type TEXT DEFAULT 'Participation',
  position TEXT,
  image_url TEXT
);

CREATE TABLE IF NOT EXISTS public."users" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  user_id UUID,
  name TEXT,
  email TEXT UNIQUE NOT NULL,
  role TEXT DEFAULT 'admin',
  permissions TEXT DEFAULT 'RnVsbA=='
);
`;

/**
 * Execute SQL Query on Supabase using Management API Personal Access Token
 */
export async function executeSupabaseSQL({ projectRef, accessToken, sqlQuery }) {
  if (!projectRef || !accessToken) {
    throw new Error("Project Ref and Supabase Personal Access Token are required.");
  }

  const response = await fetch(
    `https://api.supabase.com/v1/projects/${projectRef}/database/query`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ query: sqlQuery }),
    },
  );

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.message || `Failed to execute SQL (Status: ${response.status})`);
  }

  return await response.json();
}

/**
 * Set Supabase Edge Function Secrets via Management API
 */
export async function setSupabaseSecrets({ projectRef, accessToken, secrets }) {
  if (!projectRef || !accessToken) {
    throw new Error("Project Ref and Supabase Personal Access Token are required.");
  }

  const secretsArray = Object.entries(secrets).map(([name, value]) => ({
    name,
    value: String(value),
  }));

  const response = await fetch(`https://api.supabase.com/v1/projects/${projectRef}/secrets`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(secretsArray),
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.message || `Failed to set secrets (Status: ${response.status})`);
  }

  return await response.json().catch(() => ({ success: true }));
}

/**
 * Verify Supabase Project Details via Management API
 */
export async function verifySupabaseProject({ projectRef, accessToken }) {
  if (!projectRef || !accessToken) {
    throw new Error("Project Ref and Supabase Personal Access Token are required.");
  }

  const response = await fetch(`https://api.supabase.com/v1/projects/${projectRef}`, {
    method: "GET",
    headers: {
      Authorization: `Bearer ${accessToken}`,
    },
  });

  if (!response.ok) {
    const err = await response.json().catch(() => ({}));
    throw new Error(err.message || `Unable to access project ${projectRef}`);
  }

  return await response.json();
}
